# Generated by Django 6.0.5

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationSubmission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("business_name", models.CharField(blank=True, max_length=255)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("product_name", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(max_length=120),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Verified", "Verified"), ("In Review", "In Review"), ("Flagged", "Flagged")],
                        default="In Review",
                        max_length=20,
                    ),
                ),
                (
                    "badge_tier",
                    models.CharField(
                        choices=[("Gold", "Gold"), ("Silver", "Silver"), ("Bronze", "Bronze")],
                        default="Bronze",
                        max_length=20,
                    ),
                ),
                ("verified_at_label", models.CharField(max_length=120)),
                ("form_data", models.JSONField(default=dict)),
                ("report_data", models.JSONField(default=dict)),
                ("activity_data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="submissions", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuthToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(db_index=True, max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="api_tokens", to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UploadedEvidence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("size", models.PositiveIntegerField(default=0)),
                ("content_type", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_evidence",
                        to="core.verificationsubmission",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="verificationsubmission",
            index=models.Index(fields=["user", "-created_at"], name="core_verifi_user_id_1d22a2_idx"),
        ),
        migrations.AddIndex(
            model_name="verificationsubmission",
            index=models.Index(fields=["contact_email"], name="core_verifi_contact_718360_idx"),
        ),
    ]
